apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: 72396544/online_inference:1.0.0
      name: online-inference
      ports:
        - containerPort: 5432